### ISSUE TITLE
Issues related to connector schema and auth

### ISSUE THREAD

**Issue by tuteng** [streamnative/function-mesh#137] opened 2021-04-23 03:48 UTC
Instance command:

```
clientAuthenticationPlugin=org.apache.pulsar.client.impl.auth.AuthenticationToken
clientAuthenticationParameters=authtoken
java -cp /pulsar/instances/java-instance.jar:/pulsar/lib/org.apache.httpcomponents-httpclient-4.5.13.jar:/pulsar/lib/org.apache.httpcomponents-httpcore-4.4.13.jar:/pulsar/lib/pulsar-client-auth-oauth2-0.2.0.jar
      -Dpulsar.functions.instance.classpath=/pulsar/lib/* -Dlog4j.configurationFile=kubernetes_instance_log4j2.xml
      -Dpulsar.function.log.dir=logs/functions -Dpulsar.function.log.file=-${SHARD_ID}
      -Xmx1073741824 org.apache.pulsar.functions.instance.JavaInstanceMain --jar /pulsar/connectors/pulsar-io-debezium-mongodb-2.8.0-rc-202104082206.nar
      --instance_id ${SHARD_ID} --function_id ${SHARD_ID}-1619100739 --function_version
      0 --function_details '{"namespace":"streamnative","name":"debezium-mongo-source-test","className":"org.apache.pulsar.functions.api.utils.IdentityFunction","userConfig":"{\"database.whitelist\":\"inventory\",\"key.converter\":\"org.apache.kafka.connect.json.JsonConverter\",\"mongodb.hosts\":\"rs0/mongo-dbz-0.mongo.default.svc.cluster.local:27017,rs0/mongo-dbz-1.mongo.default.svc.cluster.local:27017,rs0/mongo-dbz-2.mongo.default.svc.cluster.local:27017\",\"mongodb.name\":\"dbserver1\",\"mongodb.password\":\"dbz\",\"mongodb.task.id\":\"1\",\"mongodb.user\":\"debezium\",\"pulsar.service.url\":\"pulsar://test-cluster-broker.streamnative.svc.cluster.local:6650\",\"value.converter\":\"org.apache.kafka.connect.json.JsonConverter\"}","secretsMap":"null","autoAck":true,"parallelism":1,"source":{"className":"org.apache.pulsar.io.debezium.mongodb.DebeziumMongoDbSource","configs":"{\"database.whitelist\":\"inventory\",\"key.converter\":\"org.apache.kafka.connect.json.JsonConverter\",\"mongodb.hosts\":\"rs0/mongo-dbz-0.mongo.default.svc.cluster.local:27017,rs0/mongo-dbz-1.mongo.default.svc.cluster.local:27017,rs0/mongo-dbz-2.mongo.default.svc.cluster.local:27017\",\"mongodb.name\":\"dbserver1\",\"mongodb.password\":\"dbz\",\"mongodb.task.id\":\"1\",\"mongodb.user\":\"debezium\",\"pulsar.service.url\":\"pulsar://test-cluster-broker.streamnative.svc.cluster.local:6650\",\"value.converter\":\"org.apache.kafka.connect.json.JsonConverter\"}","typeClassName":"org.apache.pulsar.common.schema.KeyValue"},"sink":{"typeClassName":"org.apache.pulsar.common.schema.KeyValue","topic":"public/streamnative/debezium-mongo-test-topic","producerSpec":{}},"resources":{"cpu":1,"ram":"1073741824"},"componentType":"SOURCE"}'
      --pulsar_serviceurl $brokerServiceURL --max_buffered_tuples 100 --port 9093
      --metrics_port 9094 --expected_healthcheck_interval -1 --cluster_name test-cluster
      --client_auth_plugin $clientAuthenticationPlugin --client_auth_params $clientAuthenticationParameters
      --use_tls $useTls
```

Client side
```
org.apache.pulsar.client.api.PulsarClientException$AuthenticationException: Unable to authenticate
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:920) ~[java-instance.jar:?]
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:94) ~[pulsar-client-original-2.7.1.jar:2.7.1]
	at org.apache.pulsar.io.kafka.connect.PulsarOffsetBackingStore.start(PulsarOffsetBackingStore.java:146) [pulsar-io-kafka-connect-adaptor-2.7.1.jar:?]
	at org.apache.pulsar.io.kafka.connect.AbstractKafkaConnectSource.open(AbstractKafkaConnectSource.java:108) [pulsar-io-kafka-connect-adaptor-2.7.1.jar:?]
```

broker side:
```
Failed to authenticate: operation=connect, principal=null, reason=No anonymous role, and no authentication provider configured
```

client side

```
 failed to get schema : org.apache.pulsar.client.api.PulsarClientException: Disconnected from server a
```

server side

```
WARN  org.apache.pulsar.broker.service.ServerCnx - [/10.100.11.73:49354] Got exception java.lang.IllegalStateException: Field 'schema_version' is not set
        at org.apache.pulsar.common.api.proto.CommandGetSchema.getSchemaVersionSlice(CommandGetSchema.java:90)
        at org.apache.pulsar.common.api.proto.CommandGetSchema.getSchemaVersion(CommandGetSchema.java:83)
        at org.apache.pulsar.broker.service.ServerCnx.handleGetSchema(ServerCnx.java:1705)
        at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:325)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:200)
        at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:162)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by nlu90** [comment] 2021-05-18 01:16
After a through investigation, it turns out that there's some error in the configuration. After updating the auth config and reset the pulsar cluster address, we are fine.

**Comment by nlu90** [comment] 2021-05-18 18:29
https://github.com/apache/pulsar/issues/10629

**Comment by nlu90** [comment] 2021-05-19 23:27
The root cause is the debezium connector creates its own pulsar client without using the correct auth. This problem should be fixed in apache/pulsar.

**Closed by nlu90** 2021-05-19 23:27 UTC
Labels: help wanted
